.github/workflows/build.yml, .github/workflows/checkpatch.yml, .github/workflows/compliance.yml
This patch enables minimal CI for finch-flight-software.
Build obc and pay apps against nucleo boards, and native_sim (remove native_sim and replace it with obc and pay boards when they become available; perhaps keep nucleo boards with overlays).
Run checkpatch.pl.
Run a compliance check on every commit in a PR.
=> ci: enable minimal CI

CODEOWNERS
With `*`, CODEOWNERS are automatically added as PR reviewers.
=> CODEOWNERS: add * to specify all files

scripts/compliance.pl
The current implementation of compliance.pl always returns zero, regardless of the result.
Ensure the script exits with a non‑zero value on failure so that GitHub Actions CI correctly detects a failed check.
=> compliance: return non-zero when check fails

README.md
This commit adds a "Getting Started" guide.
The guide currently only supports Ubuntu 24.04 LTS with x86_64
processors because it utilizes scripts under `./scripts`.
Some packages are not available on other processor architectures.
=> README: add "Getting Started" guide

.github/workflows/build.yml, .github/workflows/checkpatch.yml, .github/workflows/compliance.yml
"synchronized" is not a valid activity type.
Change "synchronized" to "synchronize" to ensure
workflows are triggered.
=> ci: correct invalid activity type

west.yml
Bump Zephyr version from v4.0.0 to v4.1.0.
=> manifest: bump Zephyr

scripts/install_dependencies.sh
The apt upgrade operation is unnecessary and creates potential failure points for CI. Therefore, remove it.
=> scripts: install_dependencies: remove apt upgrade

.github/workflows/dnm.yml, scripts/dnm.py
Adds a Python script and a GitHub Actions workflow to automatically block merging of pull requests if a DNM label is found
=> ci: add DNM script and workflow to block merging PRs with DNM label

.github/workflows/cppcheck.yml, scripts/run_cppcheck.sh
Add a script for static code analysis (cppcheck) and integrate it into the CI workflow.
=> ci: enable static code analysis

.github/workflows/build.yml
Before the commit, the build workflow only checks the last commit at the time of a trigger. This commit updates the CI, so that every build check is done on all PR commits.
See the issue #23 in finch-flight-software for more details.
=> CI: make sure all commits in a PR are buildable.

scripts/run_checkpatch.sh
This patch extends checkpatch.pl coverage to include Devicetree files such as .dts, .dtsi, and .overlay.
=> scripts: run_checkpatch: apply checkpatch to Devicetree files

README.md
Previously, under the 'Getting Started' section, all subsection headers were sized at ##, which made the markdown render look a little bit noisy. Use ### instead.
=> README: reduce header size under 'Getting Started' section

scripts/run_cppcheck.sh
The build directory should not be included in cppcheck otherwise certain macros and definitions in the build files will cause cppcheck to throw an error. And we want cppcheck to check just our source code.
=> scripts: run_cppcheck: exclude build directory in cppcheck

.github/workflows/build.yml
This PR removes the CI build check for the OBC app targeting the native_sim board and adds OBC target, since OBC is now ready and development using peripherals that are not supported by native_sim is anticipated.
=> ci: add OBC app build check for OBC target and remove native_sim target

.github/workflows/build-only.yml
Add GitHub Actions workflow to build all libraries.
Ideally all libraries would have tests, but this could act as a sort of smoke test that runs really fast.
=> .github: workflows: add build library workflow

scripts/setup_west_workspace.sh
The echo line in this script can be misleading unless the script is executed specifically as part of setting up a new FINCH flight software development environment along with other scripts, which is not necessarily the case. Also, this print didn’t add much value in the first place.
=> scripts: setup_west_workspace: remove a potentially misleading print

scripts/setup_west_workspace.sh
All MCUs on the FINCH CubeSat are 32-bit ARM processors. Therefore, only install the arm-zephyr-eabi toolchain.
=> scripts: setup_west_workspace: only install arm-zephyr-eabi

.gitattributes
All files have their line endings normalized using git.
Two exceptions are .sh and .ps1 scripts: .sh scripts need LF line endings to run them properly, and .ps1 scripts use CRLF by convention.
From git documentation:
When a matching file is added to the index, the file’s line endings are normalized to LF in the index. Conversely, when the file is copied from the index to the working directory, its line endings may be converted from LF to CRLF depending on the eol attribute, the Git config, and the platform.
=> .gitattributes: set line endings for all files

.github/workflows/build.yml, boards/pay/Kconfig.pay, boards/pay/board.cmake, boards/pay/board.yml, boards/pay/pay.dts
Initial devicetree includes bare minimum nodes: debug leds, HSE, PLL,
RCC and flash.
SYSCLK is configured to a maximum frequency (480 MHz).
=> boards: pay: add initial support for PAY 

scripts/setup_west_workspace.sh
~~The pip install step should be performed in setup_python_venv.sh, not in setup_west_workspace.sh. Additionally, use 'west packages' to install Python dependencies, rather than directly using 'pip install'.~~
Since Zephyr v4.1.0, the official "Getting Started Guide" uses
'west packages' instead of 'pip install'. Therefore, prefer
'west packages' in scripts/setup_west_workspace.sh.
See:
https://docs.zephyrproject.org/4.0.0/develop/getting_started/index.html
https://docs.zephyrproject.org/4.1.0/develop/getting_started/index.html
=> scripts: setup_west_workspace: prefer west packages over pip install

scripts/install_dependencies.sh
Currently, the following warning is generated:
WARNING: apt does not have a stable CLI interface.
Use with caution in scripts.
'apt' is intended for end users [1], while 'apt-get' is considered the back-end interface [2].
References:
[1] https://manpages.debian.org/trixie/apt/apt.8.en.html
[2] https://manpages.debian.org/trixie/apt/apt-get.8.en.html
=> scripts: install_dependencies: use 'apt-get' instead of 'apt'

scripts/setup_west_workspace.sh
This commit changes the download directory from "zephyr-sdk-x.xx.x" to "zephyr-sdk", making the name constant and predictable.
This way scripts can access tools in the Zephyr SDK using a fixed path.
=> scripts: download Zephyr SDK to zephyr-sdk folder

scripts/gdb_server.ps1
Add missing --target argument for PCB flashing. It was mistakenly removed.
=> scripts: gdb_server.ps1: add missing --target for pcb flashing

include/finch/ccsds123b/predictor.h, lib/ccsds123b/src/predictor.c, tests/ccsds123b/debug/src/reconstructor.c
Refactor initialize_weights to take the size of the weights array instead of hardcoding it in the function
=> lib: Refactor initialize_weights

CONTRIBUTING.md
Added guidelines for writing effective commit messages, including examples and formatting rules. These clarify some issues I had when writing commit messages as a new contributor, as discussed in https://github.com/utat-ss/finch-flight-software/pull/130. Note that I also added an explanation of how `[area]` works even though that was not discussed in the PR, because I think it may provide further clarification, along with providing the suggestion of `git log [FILE]`.
=> CONTRIBUTING: Improved commit message guidelines
